version: '3.4'
services: 
    db:
        image: mariadb:latest
        restart: always
        ports: 
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: openvpn-access
            MYSQL_DATABASE: openvpn_access
            MYSQL_USER: openvpn-access
            MYSQL_PASSWORD: openvpn-access
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    backend:
        build: 
            context: ./backend
            dockerfile: ./docker/Dockerfile
        ports:
            - 3000:8080
        environment: 
            MYSQL_PASSWORD: openvpn-access
        logging: 
            driver: json-file
    openvpn:
        build: ./openvpn-docker
